### ISSUE TITLE
error while creating or editing a issues

### ISSUE THREAD

**Issue by burggmbh** [guilhermenoronha/redmine_send_mails#8]
We recieve an  500 Internal Server while creating or editing an issue.
We're using Redmine 2.4.1
I think this is the problem, could you please update the plugin.
We would reallyreally like to use your plugin.

Here is the log:

Completed 500 Internal Server Error in 87.1ms

NoMethodError (undefined method `save_issue_with_child_records' for #<Issue:0x0000000731a9a0>):
  activemodel (3.2.15) lib/active_model/attribute_methods.rb:407:in`method_missing'
  activerecord (3.2.15) lib/active_record/attribute_methods.rb:149:in `method_missing'
  plugins/redmine_send_mails/lib/issues/issues_controller_patch.rb:26:in`update_with_send_mail_checker_issues'
  actionpack (3.2.15) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.15) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.15) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.15) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.15) lib/active_support/callbacks.rb:491:in `_run__446259241958774331__process_action__4225630917760274378__callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.15) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.15) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.15) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.15) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.15) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.15) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.15) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.15) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.15) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  activerecord (3.2.15) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.15) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.15) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.15) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.15) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.15) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in`call'
  actionpack (3.2.15) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in`call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.15) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.15) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.15) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.15) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in `_run__3637950227641706916__call__2256114696340052106__callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.15) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.15) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.15) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.15) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.15) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.15) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.15) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.15) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.15) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/static.rb:63:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in`pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.15) lib/rails/engine.rb:484:in`call'
  railties (3.2.15) lib/rails/application.rb:231:in `call'
  railties (3.2.15) lib/rails/railtie/configurable.rb:30:in`method_missing'
  passenger (4.0.26) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.26) lib/phusion_passenger/request_handler/thread_handler.rb:140:in`accept_and_process_next_request'
  passenger (4.0.26) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
  passenger (4.0.26) lib/phusion_passenger/request_handler.rb:441:in`block (3 levels) in start_threads'

**Comment by guilhermenoronha** [comment]
I'm rewriting the plugin to achieve more compatibility between Redmine versions. When it's done I'll ask to you test the plugin again. Thanks.

**Comment by burggmbh** [comment]
Okay thank you.

**Comment by guilhermenoronha** [comment]
Hello. I've commited a beta version on master branch. Please check if this version attends you.  If you experience any error, please send me a feedback and I'll check for you. Thanks.

**Comment by burggmbh** [comment]
Thank you, i will test it

**Comment by burggmbh** [comment]
Hi, now it is another error. It appears when I'm editing an issue. Whether the "I want to send e-mail" box is checked or not, makes no difference.
The error appears also while adding a new issue.

Started PUT "/issues/47" for 192.168.0.38 at 2013-12-16 09:34:14 +0100
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"aPT3a6WQiEe/cpVn9ot+0nGFTwVlLLefsz58Y3SMee4=", "issue"=>{"is_private"=>"0", "project_id"=>"20", "tracker_id"=>"10", "subject"=>"Zugewiesn an mich 2", "description"=>"", "status_id"=>"2", "priority_id"=>"2", "assigned_to_id"=>"12", "parent_issue_id"=>"", "start_date"=>"2013-10-31", "due_date"=>"", "done_ratio"=>"0", "custom_field_values"=>{"12"=>"", "13"=>"0"}, "tag_list"=>"", "notes"=>"dsafg", "private_notes"=>"0", "lock_version"=>"1"}, "mail_checker_issue"=>"1", "time_entry"=>{"hours"=>"", "activity_id"=>"", "comments"=>""}, "last_journal_id"=>"190", "commit"=>"OK", "id"=>"47"}
   (0.3ms)  SELECT MAX(`settings`.`updated_on`) AS max_id FROM `settings`
  User Load (0.2ms)  SELECT `users`.\* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 3 LIMIT 1
  Current user: mm (id=3)
   (0.2ms)  SELECT MAX(`contacts_settings`.`updated_on`) AS max_id FROM `contacts_settings`
  Issue Load (0.2ms)  SELECT `issues`.\* FROM `issues` WHERE `issues`.`id` = 47 LIMIT 1
  Project Load (0.2ms)  SELECT `projects`.\* FROM `projects` WHERE `projects`.`id` = 20 LIMIT 1
  SQL (0.2ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 20
  TimeEntryActivity Load (0.2ms)  SELECT `enumerations`.\* FROM `enumerations` WHERE `enumerations`.`type` IN ('TimeEntryActivity') AND `enumerations`.`is_default` = 1 ORDER BY enumerations.position ASC LIMIT 1
  Tracker Load (0.2ms)  SELECT `trackers`.\* FROM `trackers` WHERE `trackers`.`id` = 10 LIMIT 1
  IssueCustomField Load (0.2ms)  SELECT `custom_fields`.\* FROM `custom_fields` INNER JOIN `custom_fields_trackers` ON `custom_fields`.`id` = `custom_fields_trackers`.`custom_field_id` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND `custom_fields_trackers`.`tracker_id` = 10
  IssueCustomField Load (0.2ms)  SELECT `custom_fields`.\* FROM `custom_fields` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND (is_for_all = 1 OR id IN (SELECT DISTINCT cfp.custom_field_id FROM custom_fields_projects cfp WHERE cfp.project_id = 20)) ORDER BY custom_fields.position ASC
  SQL (0.2ms)  SELECT `custom_values`.`id` AS t0_r0, `custom_values`.`customized_type` AS t0_r1, `custom_values`.`customized_id` AS t0_r2, `custom_values`.`custom_field_id` AS t0_r3, `custom_values`.`value` AS t0_r4, `custom_fields`.`id` AS t1_r0, `custom_fields`.`type` AS t1_r1, `custom_fields`.`name` AS t1_r2, `custom_fields`.`field_format` AS t1_r3, `custom_fields`.`possible_values` AS t1_r4, `custom_fields`.`regexp` AS t1_r5, `custom_fields`.`min_length` AS t1_r6, `custom_fields`.`max_length` AS t1_r7, `custom_fields`.`is_required` AS t1_r8, `custom_fields`.`is_for_all` AS t1_r9, `custom_fields`.`is_filter` AS t1_r10, `custom_fields`.`position` AS t1_r11, `custom_fields`.`searchable` AS t1_r12, `custom_fields`.`default_value` AS t1_r13, `custom_fields`.`editable` AS t1_r14, `custom_fields`.`visible` AS t1_r15, `custom_fields`.`multiple` AS t1_r16 FROM `custom_values` LEFT OUTER JOIN `custom_fields` ON `custom_fields`.`id` = `custom_values`.`custom_field_id` WHERE `custom_values`.`customized_id` = 47 AND `custom_values`.`customized_type` = 'Issue' ORDER BY custom_fields.position
   (0.2ms)  SELECT COUNT(_) FROM `projects` WHERE (projects.status = 1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking'))
  IssueStatus Load (0.2ms)  SELECT `issue_statuses`._ FROM `issue_statuses` WHERE `issue_statuses`.`id` = 2 LIMIT 1
  Role Load (0.2ms)  SELECT `roles`.\* FROM `roles`
  User Load (0.2ms)  SELECT `users`.\* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 3 LIMIT 1
  WorkflowTransition Load (0.2ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowTransition') AND `workflows`.`old_status_id` = 2 AND (role_id IN (1,2,3,4,9,10) AND tracker_id = 10 AND ((author = 0 AND assignee = 0) OR author = 1 OR assignee = 1))
  IssueStatus Load (0.2ms)  SELECT `issue_statuses`.\* FROM `issue_statuses` WHERE `issue_statuses`.`id` IN (6, 5, 8, 4, 3, 1)
  IssueRelation Load (0.2ms)  SELECT `issue_relations`.\* FROM `issue_relations` WHERE `issue_relations`.`issue_to_id` = 47
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  WorkflowPermission Load (0.2ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowPermission') AND `workflows`.`tracker_id` = 10 AND `workflows`.`old_status_id` = 2 AND `workflows`.`role_id` IN (1, 2, 3, 4, 9, 10)
  Project Exists (0.2ms)  SELECT 1 AS one FROM `projects` WHERE `projects`.`id` = 20 AND (projects.status = 1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) LIMIT 1
  CACHE (0.0ms)  SELECT `trackers`.\* FROM `trackers` WHERE `trackers`.`id` = 10 LIMIT 1
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowPermission') AND `workflows`.`tracker_id` = 10 AND `workflows`.`old_status_id` = 2 AND `workflows`.`role_id` IN (1, 2, 3, 4, 9, 10)
  CACHE (0.0ms)  SELECT `issue_statuses`.\* FROM `issue_statuses` WHERE `issue_statuses`.`id` = 2 LIMIT 1
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowTransition') AND `workflows`.`old_status_id` = 2 AND (role_id IN (1,2,3,4,9,10) AND tracker_id = 10 AND ((author = 0 AND assignee = 0) OR author = 1 OR assignee = 1))
  CACHE (0.0ms)  SELECT `issue_statuses`.\* FROM `issue_statuses` WHERE `issue_statuses`.`id` IN (6, 5, 8, 4, 3, 1)
  CACHE (0.0ms)  SELECT COUNT(_) FROM `projects` WHERE (projects.status = 1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking'))
  CACHE (0.0ms)  SELECT `issue_statuses`._ FROM `issue_statuses` WHERE `issue_statuses`.`id` = 2 LIMIT 1
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowTransition') AND `workflows`.`old_status_id` = 2 AND (role_id IN (1,2,3,4,9,10) AND tracker_id = 10 AND ((author = 0 AND assignee = 0) OR author = 1 OR assignee = 1))
  CACHE (0.0ms)  SELECT `issue_statuses`.\* FROM `issue_statuses` WHERE `issue_statuses`.`id` IN (6, 5, 8, 4, 3, 1)
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowPermission') AND `workflows`.`tracker_id` = 10 AND `workflows`.`old_status_id` = 2 AND `workflows`.`role_id` IN (1, 2, 3, 4, 9, 10)
  CACHE (0.0ms)  SELECT `custom_fields`.\* FROM `custom_fields` INNER JOIN `custom_fields_trackers` ON `custom_fields`.`id` = `custom_fields_trackers`.`custom_field_id` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND `custom_fields_trackers`.`tracker_id` = 10
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowPermission') AND `workflows`.`tracker_id` = 10 AND `workflows`.`old_status_id` = 2 AND `workflows`.`role_id` IN (1, 2, 3, 4, 9, 10)
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowPermission') AND `workflows`.`tracker_id` = 10 AND `workflows`.`old_status_id` = 2 AND `workflows`.`role_id` IN (1, 2, 3, 4, 9, 10)
  CACHE (0.0ms)  SELECT `issue_statuses`.\* FROM `issue_statuses` WHERE `issue_statuses`.`id` = 2 LIMIT 1
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowTransition') AND `workflows`.`old_status_id` = 2 AND (role_id IN (1,2,3,4,9,10) AND tracker_id = 10 AND ((author = 0 AND assignee = 0) OR author = 1 OR assignee = 1))
  CACHE (0.0ms)  SELECT `issue_statuses`.\* FROM `issue_statuses` WHERE `issue_statuses`.`id` IN (6, 5, 8, 4, 3, 1)
   (0.2ms)  BEGIN
  ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.\* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 47 AND `taggings`.`taggable_type` = 'Issue' AND (taggings.context = 'tags' AND taggings.tagger_id IS NULL)
  CACHE (0.0ms)  SELECT `tags`.\* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 47 AND `taggings`.`taggable_type` = 'Issue' AND (taggings.context = 'tags' AND taggings.tagger_id IS NULL)
  SQL (0.2ms)  SELECT `users`.id FROM `users` INNER JOIN `watchers` ON `users`.`id` = `watchers`.`user_id` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `watchers`.`watchable_id` = 47 AND `watchers`.`watchable_type` = 'Issue'
  User Load (0.2ms)  SELECT `users`.\* FROM `users` INNER JOIN `watchers` ON `users`.`id` = `watchers`.`user_id` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `watchers`.`watchable_id` = 47 AND `watchers`.`watchable_type` = 'Issue'
  IssuePriority Load (0.2ms)  SELECT `enumerations`.\* FROM `enumerations` WHERE `enumerations`.`type` IN ('IssuePriority') AND `enumerations`.`id` = 2 ORDER BY enumerations.position ASC LIMIT 1
  CACHE (0.0ms)  SELECT `issue_statuses`.\* FROM `issue_statuses` WHERE `issue_statuses`.`id` = 2 LIMIT 1
  CACHE (0.0ms)  SELECT `roles`.\* FROM `roles`
  CACHE (0.0ms)  SELECT `workflows`.\* FROM `workflows` WHERE `workflows`.`type` IN ('WorkflowPermission') AND `workflows`.`tracker_id` = 10 AND `workflows`.`old_status_id` = 2 AND `workflows`.`role_id` IN (1, 2, 3, 4, 9, 10)
   (0.8ms)  UPDATE `issues` SET `assigned_to_id` = 12, `updated_on` = '2013-12-16 09:34:14', `lock_version` = 2 WHERE (`issues`.`id` = 47 AND `issues`.`lock_version` = 1)
  SQL (0.4ms)  INSERT INTO `custom_values` (`custom_field_id`, `customized_id`, `customized_type`, `value`) VALUES (12, 47, 'Issue', NULL)
  SQL (0.3ms)  INSERT INTO `custom_values` (`custom_field_id`, `customized_id`, `customized_type`, `value`) VALUES (13, 47, 'Issue', NULL)
   (0.3ms)  UPDATE `custom_values` SET `value` = '' WHERE `custom_values`.`id` = 169
   (0.2ms)  UPDATE `custom_values` SET `value` = '0' WHERE `custom_values`.`id` = 170
  SQL (0.3ms)  INSERT INTO `journals` (`created_on`, `journalized_id`, `journalized_type`, `notes`, `private_notes`, `user_id`) VALUES ('2013-12-16 09:34:14', 47, 'Issue', 'dsafg', 0, 3)
  SQL (0.3ms)  INSERT INTO `journal_details` (`journal_id`, `old_value`, `prop_key`, `property`, `value`) VALUES (395, 3, 'assigned_to_id', 'attr', 12)
  SQL (0.2ms)  INSERT INTO `journal_details` (`journal_id`, `old_value`, `prop_key`, `property`, `value`) VALUES (395, NULL, 13, 'cf', '0')
  Issue Load (0.4ms)  SELECT `issues`.\* FROM `issues` WHERE `issues`.`id` = 47 LIMIT 1
  User Load (0.2ms)  SELECT `users`.\* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 3 LIMIT 1
  Principal Load (0.2ms)  SELECT `users`.\* FROM `users` WHERE `users`.`id` = 12 LIMIT 1
  Project Load (0.2ms)  SELECT `projects`.\* FROM `projects` WHERE `projects`.`id` = 20 LIMIT 1
  SQL (0.3ms)  SELECT `members`.`id` AS t0_r0, `members`.`user_id` AS t0_r1, `members`.`project_id` AS t0_r2, `members`.`created_on` AS t0_r3, `members`.`mail_notification` AS t0_r4, `users`.`id` AS t1_r0, `users`.`login` AS t1_r1, `users`.`hashed_password` AS t1_r2, `users`.`firstname` AS t1_r3, `users`.`lastname` AS t1_r4, `users`.`mail` AS t1_r5, `users`.`admin` AS t1_r6, `users`.`status` AS t1_r7, `users`.`last_login_on` AS t1_r8, `users`.`language` AS t1_r9, `users`.`auth_source_id` AS t1_r10, `users`.`created_on` AS t1_r11, `users`.`updated_on` AS t1_r12, `users`.`type` AS t1_r13, `users`.`identity_url` AS t1_r14, `users`.`mail_notification` AS t1_r15, `users`.`salt` AS t1_r16, `users`.`must_change_passwd` AS t1_r17, `users`.`reminder_notification` AS t1_r18, `roles`.`id` AS t2_r0, `roles`.`name` AS t2_r1, `roles`.`position` AS t2_r2, `roles`.`assignable` AS t2_r3, `roles`.`builtin` AS t2_r4, `roles`.`permissions` AS t2_r5, `roles`.`issues_visibility` AS t2_r6 FROM `members` LEFT OUTER JOIN `users` ON `users`.`id` = `members`.`user_id` LEFT OUTER JOIN `member_roles` ON `member_roles`.`member_id` = `members`.`id` LEFT OUTER JOIN `roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `members`.`project_id` = 20 AND (users.type='User' AND users.status=1)
  SQL (0.2ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 20
  SQL (0.2ms)  SELECT DISTINCT `members`.id FROM `members` LEFT OUTER JOIN `projects` ON `projects`.`id` = `members`.`project_id` LEFT OUTER JOIN `member_roles` ON `member_roles`.`member_id` = `members`.`id` LEFT OUTER JOIN `roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `members`.`user_id` = 12 AND `members`.`project_id` = 20 AND (projects.status<>9) ORDER BY projects.name LIMIT 1
  SQL (0.2ms)  SELECT `members`.`id` AS t0_r0, `members`.`user_id` AS t0_r1, `members`.`project_id` AS t0_r2, `members`.`created_on` AS t0_r3, `members`.`mail_notification` AS t0_r4, `projects`.`id` AS t1_r0, `projects`.`name` AS t1_r1, `projects`.`description` AS t1_r2, `projects`.`homepage` AS t1_r3, `projects`.`is_public` AS t1_r4, `projects`.`parent_id` AS t1_r5, `projects`.`created_on` AS t1_r6, `projects`.`updated_on` AS t1_r7, `projects`.`identifier` AS t1_r8, `projects`.`status` AS t1_r9, `projects`.`lft` AS t1_r10, `projects`.`rgt` AS t1_r11, `projects`.`inherit_members` AS t1_r12, `projects`.`section_id` AS t1_r13, `roles`.`id` AS t2_r0, `roles`.`name` AS t2_r1, `roles`.`position` AS t2_r2, `roles`.`assignable` AS t2_r3, `roles`.`builtin` AS t2_r4, `roles`.`permissions` AS t2_r5, `roles`.`issues_visibility` AS t2_r6 FROM `members` LEFT OUTER JOIN `projects` ON `projects`.`id` = `members`.`project_id` LEFT OUTER JOIN `member_roles` ON `member_roles`.`member_id` = `members`.`id` LEFT OUTER JOIN `roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `members`.`user_id` = 12 AND `members`.`project_id` = 20 AND `members`.`id` IN (322) AND (projects.status<>9) ORDER BY projects.name
  User Load (0.2ms)  SELECT `users`.\* FROM `users` INNER JOIN `watchers` ON `users`.`id` = `watchers`.`user_id` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `watchers`.`watchable_id` = 47 AND `watchers`.`watchable_type` = 'Issue' AND `users`.`status` = 1
  CustomField Load (0.2ms)  SELECT `custom_fields`.\* FROM `custom_fields` WHERE `custom_fields`.`id` = 13 LIMIT 1
  Tracker Load (0.2ms)  SELECT `trackers`.\* FROM `trackers` WHERE `trackers`.`id` = 10 LIMIT 1
  IssueCustomField Load (0.2ms)  SELECT `custom_fields`.\* FROM `custom_fields` INNER JOIN `custom_fields_trackers` ON `custom_fields`.`id` = `custom_fields_trackers`.`custom_field_id` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND `custom_fields_trackers`.`tracker_id` = 10
  IssueCustomField Load (0.2ms)  SELECT `custom_fields`.\* FROM `custom_fields` WHERE `custom_fields`.`type` IN ('IssueCustomField') AND (is_for_all = 1 OR id IN (SELECT DISTINCT cfp.custom_field_id FROM custom_fields_projects cfp WHERE cfp.project_id = 20)) ORDER BY custom_fields.position ASC
  SQL (1.2ms)  SELECT `custom_values`.`id` AS t0_r0, `custom_values`.`customized_type` AS t0_r1, `custom_values`.`customized_id` AS t0_r2, `custom_values`.`custom_field_id` AS t0_r3, `custom_values`.`value` AS t0_r4, `custom_fields`.`id` AS t1_r0, `custom_fields`.`type` AS t1_r1, `custom_fields`.`name` AS t1_r2, `custom_fields`.`field_format` AS t1_r3, `custom_fields`.`possible_values` AS t1_r4, `custom_fields`.`regexp` AS t1_r5, `custom_fields`.`min_length` AS t1_r6, `custom_fields`.`max_length` AS t1_r7, `custom_fields`.`is_required` AS t1_r8, `custom_fields`.`is_for_all` AS t1_r9, `custom_fields`.`is_filter` AS t1_r10, `custom_fields`.`position` AS t1_r11, `custom_fields`.`searchable` AS t1_r12, `custom_fields`.`default_value` AS t1_r13, `custom_fields`.`editable` AS t1_r14, `custom_fields`.`visible` AS t1_r15, `custom_fields`.`multiple` AS t1_r16 FROM `custom_values` LEFT OUTER JOIN `custom_fields` ON `custom_fields`.`id` = `custom_values`.`custom_field_id` WHERE `custom_values`.`customized_id` = 47 AND `custom_values`.`customized_type` = 'Issue' ORDER BY custom_fields.position
  Role Load (0.2ms)  SELECT `roles`.\* FROM `roles` INNER JOIN `custom_fields_roles` ON `roles`.`id` = `custom_fields_roles`.`role_id` WHERE `custom_fields_roles`.`custom_field_id` = 12
   (53.6ms)  ROLLBACK
Completed 500 Internal Server Error in 349.0ms

ArgumentError (wrong number of arguments (3 for 1)):
  app/models/mailer.rb:422:in `initialize'
  app/models/mailer.rb:445:in`method_missing'
  app/models/mailer.rb:86:in `block (2 levels) in deliver_issue_edit'
  app/models/issue.rb:818:in`block in each_notification'
  app/models/issue.rb:817:in `each'
  app/models/issue.rb:817:in`each_notification'
  app/models/mailer.rb:85:in `block in deliver_issue_edit'
  app/models/journal.rb:77:in`block in each_notification'
  app/models/journal.rb:75:in `each'
  app/models/journal.rb:75:in`each_notification'
  app/models/mailer.rb:84:in `deliver_issue_edit'
  app/models/journal.rb:190:in`send_notification'
  app/models/journal.rb:54:in `save'
  app/models/issue.rb:1506:in`create_journal'
  app/models/issue.rb:163:in `create_or_update'
  app/controllers/issues_controller.rb:470:in`block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:458:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:184:in`update'

**Comment by burggmbh** [comment]
Are there any new information about the solution?
How is the progress?

**Comment by jarrettchisholm** [comment]
@burggmbh, you might check out my [pull request](https://github.com/guilhermenoronha/redmine_send_mails/pull/10) - it fixes the mail issues for redmine `issues`.  The fix is for Redmine 2.4.2.  Doesn't seem to work yet for wiki updates (not sure why...)

**Comment by igor-panassiouk** [comment]
Similar problem was after **migration from 2.3.0 to 2.6.6**

Completed 500 Internal Server Error in 2382.9ms

ArgumentError (wrong number of arguments (3 for 1)):
  app/models/mailer.rb:423:in `initialize'
  app/models/mailer.rb:446:in`method_missing'
  app/models/mailer.rb:52:in `block in deliver_issue_add'
  app/models/issue.rb:848:in`each_notification'
  app/models/mailer.rb:51:in `deliver_issue_add'
  app/models/issue.rb:1570:in`send_notification'
  app/models/issue.rb:165:in `create_or_update'
  app/controllers/issues_controller.rb:150:in`create'

Patch solved it, thank you!
